namespace: sre

generators:
- |-
  apiVersion: v1
  kind: krmFn
  metadata:
    name: local
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: "fnRenderGotpl"
  spec:
    templates: ./manifests
    context: ./context.yaml
